Add files via upload
Unistall

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,30 +1,18 @@
 #!/sbin/sh
-# Kali NetHunter Remove
+# Kali NetHunter uninstaller (does not currently do anything useful, anyone wanna take it on?)
 
-## start build generated variables
-supersu=
-## end build generated variables
-
-if [ "$3" ]; then
+[ "$3" ] && {
 	zip=$3
 	console=/proc/$$/fd/$2
 	# write the location of the console buffer to /tmp/console for other scripts to use
 	echo "$console" > /tmp/console
-else
+} || {
 	console=$(cat /tmp/console)
 	[ "$console" ] || console=/proc/$$/fd/1
-fi
-
-tmp=/tmp/nethunter
-patchtmp=$tmp/boot-patcher
-sutmp=/tmp/supersu
-
-progress() {
-	echo "set_progress $1" > "$console"
 }
 
 print() {
-	echo "ui_print ${1:- }" > "$console"
+	echo "ui_print $1" > $console
 	echo
 }
 
@@ -34,7 +22,7 @@ abort() {
 		print "Aborting..."
 	}
 	cleanup
-	print "Failed to install Kali NetHunter!"
+	print "Failed to uninstall!"
 	exit 1
 }
 
@@ -47,32 +35,44 @@ cleanup() {
 	[ "$zip" ] && rm /tmp/console
 }
 
-print "##################################################"
-print "##################################################"
-print "##                                              ##"
-print "##  88      a8P         db        88        88  ##"
-print "##  88    .88'         d88b       88        88  ##"
-print "##  88   88'          d8''8b      88        88  ##"
-print "##  88 d88           d8'  '8b     88        88  ##"
-print "##  8888'88.        d8YaaaaY8b    88        88  ##"
-print "##  88P   Y8b      d8''''''''8b   88        88  ##"
-print "##  88     '88.   d8'        '8b  88        88  ##"
-print "##  88       Y8b d8'          '8b 888888888 88  ##"
-print "##                                              ##"
-print "###################Auto Remove####################"
-print "################### NetHunter ####################"
+mount() {
+	mountpoint -q "$1" || /sbin/busybox mount -o rw "$1" || abort "Unable to mount $1 as rw!"
+	>> "$1/.rw" && return || /sbin/busybox mount -o remount,rw "$1"
+	>> "$1/.rw" && return || abort "Unable to write to $1!"
+}
 
+print "***********************"
+print " NetHunter Uninstaller "
+print "***********************"
 
-print "Checking and Remove for previous versions of NetHunter"
-sh tools/prevremove.sh
+mount /system
+mount /data
 
-progress 0.9
+# Remove added firmware (folder would only exist if you installed NetHunter)
+[ -d "/system/etc/firmware/rtlwifi" ] && {
+	print "@Removing Firmware";
+	rm -rf /system/etc/firmware/rtlwifi
+	rm -rf /system/etc/firmware/zd1211
+	rm -f /system/etc/firmware/ar9170-1.fw
+	rm -f /system/etc/firmware/ar9170-2.fw
+	rm -f /system/etc/firmware/carl9170.fw
+	rm -f /system/etc/firmware/htc_7010.fw
+	rm -f /system/etc/firmware/rt73.bin
+	rm -f /system/etc/firmware/rt2561.bin
+	rm -f /system/etc/firmware/rt2860.bin
+	rm -f /system/etc/firmware/rt2870.bin
+	rm -f /system/etc/firmware/rt3070.bin
+}
 
-print "Running Kali chroot Remove..."
-sh tools/removechroot.sh "$zip"
+[ -d "/system/priv-app/NetHunter" ] && {
+	print "@Removing NetHunter.apk"
+	rm -rf /system/priv-app/NetHunter
+}
+
+[ -d "/data/data/com.offsec.nethunter" ] && {
+	print "@Removing NetHunter chroot/data"
+	rm -rf /data/data/com.offsec.nethunter
+}
 
 cleanup
-print "************************************************"
-print "*       Kali NetHunter is now Remove!          *"
-print "************************************************"
-progress 1.0
+print "@Uninstall complete"
